import type { Metadata } from "next";

import { Header } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "zilog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <link
        href="http://cdn.jsdelivr.net/gh/joungkyun/font-d2coding/d2coding.css"
        rel="stylesheet"
        type="text/css"
      />
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
