import type { Metadata } from "next";
import Head from "next/head";

import { Header } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "zilog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="http://cdn.jsdelivr.net/gh/joungkyun/font-d2coding/d2coding.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <body className="flex flex-col items-center">
        <Header />
        {children}
      </body>
    </html>
  );
}
